check clear session 8
iseruuuuu/flutter_yumemi_training_app pull request #26
Opened 2023-10-10 01:18 UTC by iseruuuuu

## 課題

close #ISSUE_NUMBER

## 対応箇所

- [ ] xxx

## 動作

| expected | actual |
|----------|--------|
| xxx      | xxx    |

2023-10-10 01:35 UTC, iseruuuuu commented on .gitattributes
> +*.g.dart linguist-generated=true
FlutterKaigi のような ↓ の設定を参考にして追記しました。
https://github.com/FlutterKaigi/2023/blob/main/.gitattributes

2023-10-10 02:58 UTC, blendthink reviewed
@iseruuuuu 
いったんコメントさせていただきましたのでご確認お願いします 🙏

2023-10-10 02:58 UTC, blendthink commented on build.yaml
> +            - require_trailing_commas
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg)
この変更をした理由や参考にしたものは何かありますか？

ぱっと見、現状だと次のようにすると警告もなくなっていいかなと思いました。
```yaml
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - type=lint
            - duplicate_ignore
```

2023-10-10 02:58 UTC, blendthink commented on lib/constants/error_message.dart
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
テキストをこのようにまとめておくことで、保守性が向上してステキだなと思いました✨

2023-10-10 02:58 UTC, blendthink commented on lib/screen/weather_screen.dart
> +    required this.ref,
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
`WidgetRef` を受け渡してしまうと、適切なスコープかどうかの判断をしなければならなくなってしまい、よりコードを読む時にコストがかかってしまうようになるため、`WidgetRef` を使う場合は受け渡すのではなく `ConsumerWidget` を継承するようにして `build()` メソッドの `WidgetRef` を使うようにしたほうが保守性や可読性の観点からより適していそうです。

2023-10-10 02:58 UTC, blendthink commented on lib/screen/weather_screen_state.dart
> +  const factory WeatherScreenState.initial() = WeatherScreenStateInitial;
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
公式ドキュメントに書かれているような形式でコメント書いておくと IDE の恩恵を得られたり、 `dart doc` コマンドでのドキュメント生成でより適切に生成できたりするため、普段から意識しておくと良さそうです、、！

```suggestion
  /// 初期状態
  const factory WeatherScreenState.initial() = WeatherScreenStateInitial;
```

https://dart.dev/language/comments
https://dart.dev/tools/dart-doc

2023-10-10 02:58 UTC, blendthink commented on lib/screen/weather_screen_state.dart
> +  const factory WeatherScreenState.list({
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg) 
`list` より `data` とかのほうが適していそうかなと思いましたがいかがでしょうか？

2023-10-10 02:58 UTC, blendthink commented on lib/screen/weather_screen.dart
> +      ),
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
↓のようにすれば `_WeatherBody` を２回記述せずに済み、より違いが分かりやすくなって良さそうです。
```dart
class WeatherScreen extends ConsumerWidget {
  const WeatherScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final state = ref.watch(weatherScreenViewModelProvider());
    final (
      weatherCondition,
      maxTemperaure,
      minTemperacture,
    ) = state.when(
      initial: () => (WeatherCondition.none, '**', '**'),
      list: (weather, max, min) => (weather, max, min),
    );
    return Scaffold(
      body: _WeatherBody(
        ref: ref,
        weatherCondition: weatherCondition,
        maxTemperature: maxTemperaure,
        minTemperature: minTemperacture,
      ),
    );
  }
}
```

2023-10-10 07:56 UTC, iseruuuuu commented on lib/screen/weather_screen_state.dart
> +  const factory WeatherScreenState.initial() = WeatherScreenStateInitial;
ドキュメントのコメントについては認知はしていましたが意識ができていませんでした。
教えていただきありがとうございます🙇
こちらのCommitで修正いたしました。
[8f5e2a9](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/8f5e2a95c591b4308ccedf271106bd4e70149a30)

2023-10-10 07:59 UTC, iseruuuuu commented on lib/screen/weather_screen_state.dart
> +  const factory WeatherScreenState.list({
確かに`list`を使う場合はリストデータの取得の時は望ましいと思いましたが、今回の場合は、天気のデータを取得したいので`data`の方が適切だなと実感することができました！
こちらのCommitで修正しました！
[fix: change list -> data](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/ad74658705ecefda587856a7c63227ca3fc4fdce)
[ad74658](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/ad74658705ecefda587856a7c63227ca3fc4fdce)

2023-10-10 08:02 UTC, blendthink commented on lib/screen/weather_screen_state.dart
> +  const factory WeatherScreenState.initial() = WeatherScreenStateInitial;
@iseruuuuu 
ご対応ありがとうございます！
合わせて他の箇所も見直していただいてもいいでしょうか？

2023-10-10 08:03 UTC, iseruuuuu commented on lib/screen/weather_screen_state.dart
> +  const factory WeatherScreenState.initial() = WeatherScreenStateInitial;
そうですね。上のCommitだけだと不足していそうなので、それもできましたら再度こちらで伝えます🙇

2023-10-10 08:07 UTC, iseruuuuu commented on lib/screen/weather_screen_state.dart
> +  const factory WeatherScreenState.initial() = WeatherScreenStateInitial;
僕が確認してみた限りで修正ができているのではないかなと思っているんのですがどうでしょうか？
もしかしたら認識が間違ってい

2023-10-10 08:09 UTC, blendthink commented on lib/screen/weather_screen_state.dart
> +  const factory WeatherScreenState.initial() = WeatherScreenStateInitial;
@iseruuuuu 
コメントの記載形式について少し誤解があるようです。。
少しハドルで話せますか？

2023-10-10 08:21 UTC, iseruuuuu commented on lib/screen/weather_screen_view_model.dart
> +        /// 失敗したとしてもエラーDialogを出すだけで、stateの状態を更新しない。
//に変更が必要

2023-10-10 08:35 UTC, iseruuuuu commented on lib/screen/weather_screen_state.dart
> +  const factory WeatherScreenState.initial() = WeatherScreenStateInitial;
先ほどはハドルいただきありがとうございます！納得した上で修正ができましたのでご確認お願いします🙇
[92bb18f](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/92bb18f1785a82fee3784b38dbdd9881f851c766)

2023-10-10 08:42 UTC, iseruuuuu commented on lib/screen/weather_screen.dart
> +      ),
別のコメントで修正必要な点がありましたが、一旦、こちらのコメントの修正に取り組みました！
[4b9ab1f](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/4b9ab1fa3d2ad4521dd7e9a2717fa5badbeb94ce)

2023-10-10 08:46 UTC, iseruuuuu commented on lib/screen/weather_screen.dart
> +    required this.ref,
` 適切なスコープかどうかの判断をしなければならなくなってしまい、よりコードを読む時にコストがかかってしまう`
こちらについては全く考えていませんでした。確かに、保守性や可読性の観点を考えると教えていただいた実装の方が望ましいと納得できました！教えていただきありがとうございます🙇
[f6df9e1](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/f6df9e158ef2e1c9fe50d03a06c5a7ad4f27b20d)

2023-10-10 09:03 UTC, iseruuuuu commented on build.yaml
> +            - require_trailing_commas
自動生成した際に、生成ファイルにwarningが出現していたので一つ一つwarningをなくすために追記していました。
しかし、教えていただいた記載をすることでwarningが消えてスッキリしました！
調べてみたところ、`duplicate_ignore`をつけることで「ファイル単位で特定のルールを解析対象外にする」という内容を知らずにいました。教えていただきありがとございます🙇
[2022e15](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/2022e15f41c3f722a58a3152290c274154fdc331)

2023-10-10 09:10 UTC, blendthink commented on build.yaml
>              - strict_raw_type
![ask-badge](https://img.shields.io/badge/review-ask-yellowgreen.svg) 
@iseruuuuu 
自分が記載したようにするなら、 `type=lint` と `duplicate_ignore` 以外は不要かなと思いましたが、いかがでしょうか？

2023-10-10 09:27 UTC, iseruuuuu commented on build.yaml
>              - strict_raw_type
削除を試みて生成してみた結果不要であるとわかりました！！とても便利な記載だと再認識しました❗️
こちらで修正しました〜！
[cac9c76](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/cac9c7662fbb4ac9dbe605e05e21b333033051e6)

2023-10-11 01:13 UTC, iseruuuuu commented
@blendthink 
この後、整体に行くため、途中経過をCommitしました！
もしかしたら記載ミスや漏れがあるかもしれないので帰宅後に再度確認させてください🙇

2023-10-11 02:01 UTC, blendthink requested changes
@iseruuuuu 
いくつかコメントしましたのでご確認お願いします🙏

2023-10-11 02:01 UTC, blendthink commented on lib/constants/error_message.dart
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
他のディレクトリの命名と合わせて `constant` にしたほうが統一感出て良さそうです。

2023-10-11 02:01 UTC, blendthink commented on ARCHITECTURE.md
> +- DataStoreからデータを取得
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg)
```suggestion
- DataSourceからデータを取得
```

2023-10-11 02:01 UTC, blendthink commented on ARCHITECTURE.md
> +- エラーの際は、ダイアログを表示する。
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg)
ViewModel の呼び出しについても記載したほうが良さそうです。

また、 ViewModel の呼び出しを行っているのは Screen と _WeatherBody があるので、 Screen から View とかに名前を変更したほうがより適切そうです。

2023-10-11 02:01 UTC, blendthink commented on ARCHITECTURE.md
> +## Riverpod の Provider の依存関係図
![next-badge](https://img.shields.io/badge/review-next-blueviolet)
（修正する必要はありませんが参考までにコメント残します）
何を使って生成したのか、更新方法はどのようにするかなども記載しておくと、保守コストを下げれてより良いかなと思いました。

自動更新できる仕組みを作れるとさらに良さそうですよね💡

2023-10-11 02:01 UTC, blendthink commented on ARCHITECTURE.md
> +WeatherScreen((WeatherScreen))
![imo-badge](https://img.shields.io/badge/review-imo-skyblue.svg)
具体的な名前（WeatherScreen） は削除して、できる限り ARCHITECTURE.md を更新しなくて済むようにしたほうがいいかなと思いました。

2023-10-11 02:01 UTC, blendthink commented on lib/model/result.dart
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
このようなクラスを作成しておくと、取り扱いやすくなっていいですね✨

2023-10-11 02:01 UTC, blendthink commented on lib/repository/weather_repository.dart
> +    }
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
丁寧にエラーハンドリングしていてステキです✨

2023-10-11 02:01 UTC, blendthink commented on pubspec.yaml
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg)
公式ドキュメントで記載されている手順で導入すると `riverpod_lint` なども含めて設定できるためより良さそうです。

https://docs-v2.riverpod.dev/docs/introduction/getting_started

2023-10-11 02:01 UTC, blendthink commented on pubspec.yaml
> +  riverpod_generator: ^2.3.3
![must-badge](https://img.shields.io/badge/review-must-red.svg)
`riverpod_generator` は開発時でしか利用しないため `dev_dependencies` のほうに記述すべきなので修正お願いします。

2023-10-11 02:49 UTC, iseruuuuu commented on lib/constants/error_message.dart
とても同意できました👍
こちらで修正しました！


43245d5

修正する中で`weather_constants`よりも`weather_condition`の方がいいかなと考えこちらも修正してみました🙇

2023-10-11 02:50 UTC, blendthink commented on lib/constants/error_message.dart
> 修正する中でweather_constantsよりもweather_conditionの方がいいかなと考えこちらも修正してみました🙇

とてもいいと思います！

2023-10-11 02:51 UTC, iseruuuuu commented on ARCHITECTURE.md
> +- DataStoreからデータを取得
修正漏れでした。ご指摘いただきありがとうございます😄
こちらで修正しました！
[2ce0267](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/2ce0267ce64301ab6255070fe84193547b0d9bcb)

2023-10-11 02:53 UTC, iseruuuuu commented on ARCHITECTURE.md
> +## Riverpod の Provider の依存関係図
何を使って生成したのか、更新方法はどのようにするかなどの記載は、`README.md`に記載をするのかなと考えていましたが、この場合だと、`ARCHITECTURE.md`と`README.md`のどちらに記載したほうがいいと思いますでしょうか・・？

2023-10-11 02:57 UTC, iseruuuuu commented on ARCHITECTURE.md
> +## Riverpod の Provider の依存関係図
もし、`README.md`する場合でしたら、このPRで記載した方がいいかもしれないという前提でお伝えさせていただきます。

2023-10-11 03:00 UTC, blendthink commented on ARCHITECTURE.md
> +## Riverpod の Provider の依存関係図
どちらもメリット・デメリットあるので、どちらでもいいとは思います！
ただ、 README.md に ARCHITECTURE.md へのリンクはあったほうが良さそうですね、、！

修正する場合は、この PR で修正でいいと思います！

2023-10-11 03:00 UTC, iseruuuuu commented on ARCHITECTURE.md
> +WeatherScreen((WeatherScreen))
以下のように修正してみたところ、ARCHITECTURE.md を更新しなくて済みそうだなと理解できました。教えていただきありがとうございます🤗

こちらで修正しました。

[3c57dcc](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/3c57dccce18458a7be3907fd038d4dfbed954439)

```mermaid
flowchart TB
Riverpod

Screen(Screen)
ViewModel(ViewModel)
Repository(Repository)
DataSource(DataSource)
Screen --> ViewModel
ViewModel --> Screen
Repository --> ViewModel
ViewModel --> Repository
Repository --> DataSource
DataSource --> Repository
```

2023-10-11 03:09 UTC, iseruuuuu commented on pubspec.yaml
公式のドキュメントの確認不足でした😢
教えていただきありがとうございます！こちらで追加しました〜！
[3c57dcc](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/3c57dccce18458a7be3907fd038d4dfbed954439)

2023-10-11 03:11 UTC, iseruuuuu commented on pubspec.yaml
> +  riverpod_generator: ^2.3.3
Packageの導入が間違えていたかもしれません😢ご指摘いただきありがとうございます！
こちらで修正しました！
[b6bad90](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/b6bad9004497091103a16df87605c7858f14dd41)

2023-10-11 03:56 UTC, iseruuuuu commented on ARCHITECTURE.md
> +- エラーの際は、ダイアログを表示する。
```
また、 ViewModel の呼び出しを行っているのは Screen と _WeatherBody があるので、  
 Screen から View とかに名前を変更したほうがより適切そうです。
```
確かにそうだなと思えました。教えていただきありがとうございます！


自分なりに修正してみました！
記載ミスや内容がおかしいかの確認もお願いできたらなと思っております🙇

[9376385](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/93763857c053d68237d45370aaf2fbc3ba3fe4a7)

2023-10-11 05:38 UTC, iseruuuuu commented on ARCHITECTURE.md
> +## Riverpod の Provider の依存関係図
Slackでの確認も込めて修正してみました！！
検討した結果、ARCHITECTURE.mdに「何を使って生成したのか、更新方法はどのようにするかなど」の記載を行い、README.mdでリンクを載せると形に対応しました！


[f03d7ec](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/f03d7ece885a2591e10c6d6ace21ebdc0536d83a)

2023-10-11 05:39 UTC, iseruuuuu commented on ARCHITECTURE.md
> +## Riverpod の Provider の依存関係図
こちらPRとは別件になるかもしれませんが、README.mdの必要な記載（環境構築など）についての記載はこのPRでは行わず、別のPRで対応予定と考えています！
ご意見をいただけると幸いです🙇

2023-10-11 08:21 UTC, blendthink reviewed
@iseruuuuu 
追加でいくつかコメントしましたのでご確認お願いします 🙏

2023-10-11 08:21 UTC, blendthink commented on ARCHITECTURE.md
> +  - 失敗した(failure)場合は、エラーのダイアログを表示する
![imo-badge](https://img.shields.io/badge/review-imo-skyblue.svg) 
保守コストをかけないようにするために、このような具体的な記載は避け、より抽象的な役割のみを記載しておいたほうがいいかなと思いました。

2023-10-11 08:21 UTC, blendthink commented on ARCHITECTURE.md
> +## Riverpod の Provider の依存関係図
> README.mdの必要な記載（環境構築など）についての記載はこのPRでは行わず、別のPRで対応予定と考えています！

いいと思います！

2023-10-11 08:21 UTC, blendthink commented on ARCHITECTURE.md
> +完成図としては、[Riverpod の Provider の依存関係図](https://github.com/iseruuuuu/github_search_app/edit/main/README.md#riverpod-%E3%81%AE-provider-%E3%81%AE%E4%BE%9D%E5%AD%98%E9%96%A2%E4%BF%82%E5%9B%B3)となります。
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg)
URL に edit が入っていて自分からは開けないものになっていました。

2023-10-11 08:21 UTC, blendthink commented on README.md
> +- https://github.com/iseruuuuu/flutter_yumemi_training_app/blob/feature/session_8/ARCHITECTURE.md
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg)
main ブランチにマージされた前提で記載しないと、プルリクエストをマージしてブランチを削除したら見れなくなってしまうため注意が必要です、、！

2023-10-11 23:03 UTC, iseruuuuu commented on README.md
> +- https://github.com/iseruuuuu/flutter_yumemi_training_app/blob/feature/session_8/ARCHITECTURE.md
確かにこの問題については、記載するときにどうしようかなと思っていました。この場合だとどう記載すればいいでしょうか・・？

2023-10-11 23:09 UTC, iseruuuuu commented on ARCHITECTURE.md
> +完成図としては、[Riverpod の Provider の依存関係図](https://github.com/iseruuuuu/github_search_app/edit/main/README.md#riverpod-%E3%81%AE-provider-%E3%81%AE%E4%BE%9D%E5%AD%98%E9%96%A2%E4%BF%82%E5%9B%B3)となります。
URLのミスをしていました🙇
しかし、修正したとしても[こちらの問題](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26#discussion_r1354378870)が出現してしまうもどうにかしたいですね🤔

URLの修正はこちらで行いました！
[f4e5450](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/f4e545053e53bfa1b518f956673a093832b0b02f)

2023-10-11 23:28 UTC, iseruuuuu commented on ARCHITECTURE.md
> +  - 失敗した(failure)場合は、エラーのダイアログを表示する
保守コストを考えていませんでした。。教えていただきありがとうございます🤗

こちらで自分なりに抽象的に記載してしてみました🙇
[3f6aa1a](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/3f6aa1a55a4b9b75c453d95bef5316d67a5b4e66)

2023-10-12 02:11 UTC, blendthink reviewed
@iseruuuuu 
いくつかコメントしましたのでご確認お願いします 🙏

2023-10-12 02:11 UTC, blendthink commented on README.md
> +- https://github.com/iseruuuuu/flutter_yumemi_training_app/blob/feature/session_8/ARCHITECTURE.md
README のパスを真似て↓のようにすればいいかなと思いました、、！
https://github.com/iseruuuuu/flutter_yumemi_training_app/blob/main/ARCHITECTURE.md

2023-10-12 02:11 UTC, blendthink commented on ARCHITECTURE.md
> +完成図としては、[Riverpod の Provider の依存関係図](https://github.com/iseruuuuu/github_search_app/edit/main/README.md#riverpod-%E3%81%AE-provider-%E3%81%AE%E4%BE%9D%E5%AD%98%E9%96%A2%E4%BF%82%E5%9B%B3)となります。
↓のコメントと同様の問題が残りそうです、、！
https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26#discussion_r1354378870

2023-10-12 02:11 UTC, blendthink commented on ARCHITECTURE.md
> +  - 失敗した(failure)場合は、エラーのダイアログを表示する
`WeatherScreen` や `_WeatherBody` などを記載してしまうと、名前が変更された場合に修正する必要が出てきてしまいますので、 `ViewModel` や `Repository` の記載と同じように記載すると良さそうです、、！
また、「天気情報を表示する」などと書いてしまうと、天気以外の情報を表示する機能を作成した場合に修正する必要が出てきてしまうので、そのようなことも記載しないほうがいいかなと思いました。

2023-10-12 02:57 UTC, blendthink commented on lib/model/weather_result.dart
> +  @JsonSerializable(fieldRename: FieldRename.snake)
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
今気づいたのですが `build.yaml` で指定しているため、ここでの指定は不要そうです！
https://github.com/iseruuuuu/flutter_yumemi_training_app/blob/ec4a6e79db4de25242582f52ad24f7a160704581/build.yaml#L12-L14

```suggestion
```

2023-10-12 04:29 UTC, iseruuuuu commented on README.md
> +- https://github.com/iseruuuuu/flutter_yumemi_training_app/blob/feature/session_8/ARCHITECTURE.md
ありがとうございます！参考になります！🤗

こちらで修正してみました！
[245cfd8](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/245cfd8690e62bda0d38871122512eab7856f905)

2023-10-12 04:34 UTC, iseruuuuu commented on ARCHITECTURE.md
> +完成図としては、[Riverpod の Provider の依存関係図](https://github.com/iseruuuuu/github_search_app/edit/main/README.md#riverpod-%E3%81%AE-provider-%E3%81%AE%E4%BE%9D%E5%AD%98%E9%96%A2%E4%BF%82%E5%9B%B3)となります。
こちらについても同様の記載を行ってみました！
修正はこちらになります！

ちゃんとできているか不安なので、ご確認いただけると幸いです🙇
[d330724](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/d330724477f9df667dc6beb4f98fec2fe967f077)

2023-10-12 05:09 UTC, iseruuuuu commented on ARCHITECTURE.md
> +  - 失敗した(failure)場合は、エラーのダイアログを表示する
確かに、コメントいただいた内容を落ち着いて考えてみたところ、WeatherScreen や _WeatherBodyなどと記載するよりも`View`として書いた方が良いと納得することができました。丁寧に教えていただきありがとうございます😁
また、Viewの文言についても自分なりに修正してみました🙇
こちらが修正したものとなります。

[3bc1a98](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/3bc1a98d1ef583ab09201f5dc90feb162ce073ca)

2023-10-12 05:19 UTC, iseruuuuu commented on lib/model/weather_result.dart
> +  @JsonSerializable(fieldRename: FieldRename.snake)
削除しても問題ないと確認できたため、削除することにしました！
こちらで修正しました🙇‍♀️
[a0206e7](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/26/commits/a0206e7327be0aff6cdea06668f97ccd6e7542aa)

2023-10-12 06:49 UTC, blendthink approved these changes
ご対応ありがとうございます！
![LGTM](https://image.lgtmoon.dev/202054)

2023-10-12 08:33 UTC, iseruuuuu commented
LGTMいただきありがとうございます🙇
マージさせていただきます！！！

2023-10-12 08:33 UTC, merged