Check clear session９
iseruuuuu/flutter_yumemi_training_app pull request #27
Opened 2023-10-13 08:08 UTC by iseruuuuu

## 課題

close #10 

## 対応箇所

- [ ] [yumemi_weather](https://github.com/yumemi-inc/flutter-training-template/blob/main/packages/yumemi_weather/README.md) API の呼び出しから Widget へ通知する部分までの [Unit tests](https://docs.flutter.dev/testing#unit-tests) を書く
  - [ ] weather_data_source
  - [ ] weather_repository
  - [ ] weather_screen_view_model 

- [ ] JSON のエンコード・デコードの [Unit tests](https://docs.flutter.dev/testing#unit-tests) も書く

## 動作

今回は、テストコードの記載のため必要なしと判断し、記載はしないことにしました

| expected | actual |
|----------|--------|
| xxx      | xxx    |

2023-10-16 01:03 UTC, iseruuuuu commented on .gitattributes
> +*.mock.dart linguist-generated=true
記載方法が間違っているかも？

2023-10-16 01:06 UTC, iseruuuuu commented on lib/data_source/weather_data_source.dart
>    }
[このサイト](https://scrapbox.io/kurogoma4d-lab/Flutter%E3%81%A7%E3%83%86%E3%82%B9%E3%83%88%E3%82%B3%E3%83%BC%E3%83%89%E3%81%A0%E3%81%91%E3%81%8C%E5%A4%96%E9%83%A8%E5%8F%82%E7%85%A7%E3%81%A7%E3%81%8D%E3%82%8BWidget%E3%82%92%E7%B5%84%E3%81%BF%E3%81%9F%E3%81%8B%E3%81%A3%E3%81%9F)を参考にして、`@visibleForTesting`追記してみました

2023-10-16 01:48 UTC, iseruuuuu commented on .gitattributes
> +*.mocks.dart linguist-generated=true
`.mocks.dart`は自動生成されたファイルであり、レビューで差分を見た時にデフォルトで閉じられている状態にするため追記しました。

2023-10-16 01:48 UTC, iseruuuuu commented on lib/repository/weather_repository.dart
> +          return const Result.failure(ErrorMessage.invalidParameter);
別のPRでエラー結果が逆になってため、このPRで修正しました

2023-10-17 02:08 UTC, blendthink requested changes
@iseruuuuu 
いったんコメントしましたのでご確認お願いします 🙏

2023-10-17 02:08 UTC, blendthink commented on lib/data_source/weather_data_source.dart
> +  /// テストコード以外からの不必要な参照を防ぐ
![imo-badge](https://img.shields.io/badge/review-imo-skyblue.svg)
ぱっと見で分かるコメントは書かないようにすると、可読性が向上する場合が多いため削除したほうがいいかなと思いました。

2023-10-17 02:08 UTC, blendthink commented on lib/data_source/weather_data_source.dart
> +    return jsonDecode(weather) as Map<String, dynamic>;
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
今回のアプリでテストしたいことは、指定のクラス（ `WeatherRequest` や `WeatherResult` ）の JSON 変換の設定が正しいかどうかですので、 `WeatherRequest` や `WeatherResult` のテストファイルを作成して、そこにテストコードが記載されていたほうが自然です。

また、 `jsonEncode` や `jsonDecode` が正しく動作するかの単体テストまでアプリ側で書くのはやりすぎで、このようなことまでテストしようとするとキリがなくなってしまうため、メソッド単体でのテストは削除していいかと思います。

2023-10-17 02:08 UTC, blendthink commented on lib/repository/weather_repository.dart
> +          return const Result.failure(ErrorMessage.invalidParameter);
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
レビュー漏れてしまっていましたね、、 🙏 
ご対応ありがとうございます！

2023-10-17 02:08 UTC, blendthink commented on test/repository/weather_repository_test.dart
> +  });
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
`WeatherDataSource` のテストと同様に Riverpod を使わずにテスト書けるので修正お願いします！

2023-10-17 02:08 UTC, blendthink commented on test/repository/weather_repository_test.dart
> +    };
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
統一してこれも test_data.dart に定義して使うようにすると方針が明確になって良さそうです。

2023-10-17 02:08 UTC, blendthink commented on test/repository/weather_repository_test.dart
> +  test('Failure to get weather by other error ', () {
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
その他のエラーの場合のテストも網羅できていてステキです✨

2023-10-17 02:08 UTC, blendthink commented on test/test_data/test_data.dart
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg) 
こうやっておくと複数箇所でテストデータを定義せずに済んでとてもいいなと思いました 🙌

2023-10-17 02:08 UTC, blendthink commented on test/view_model/weather_view_model_test.dart
> +    );
![must-badge](https://img.shields.io/badge/review-must-red.svg) 
下で型のチェックも行えているためここは削除して良さそうです。

2023-10-17 02:08 UTC, blendthink commented on test/view_model/weather_view_model_test.dart
> +    container.dispose();
![must-badge](https://img.shields.io/badge/review-must-red.svg)
`tearDown()` で `container.dispose()` しているためここの記載は不要そうです。

```dart
tearDown(() {
  container.dispose();
});
```

2023-10-17 02:08 UTC, blendthink commented on test/view_model/weather_view_model_test.dart
> +  });
![imo-badge](https://img.shields.io/badge/review-imo-skyblue.svg) 
`reloadWeather()` が失敗した場合に、元々の状態が保持されているかどうかもテストしたいですね、、！

2023-10-17 02:08 UTC, blendthink commented on test/view_model/weather_view_model_test.dart
> +    );
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg)
他の箇所と同じようにして良さそうです。
また、型判定ではなく `==` 判定のほうが、より細かいところもチェックできるので特に理由がなければ `==` 判定にしてしまったほうがいいかなと思います。
```suggestion
    final state = create().state;
    expect(
      state,
      const WeatherScreenState.initial(),
    );
```

2023-10-17 22:57 UTC, iseruuuuu commented on lib/data_source/weather_data_source.dart
> +  /// テストコード以外からの不必要な参照を防ぐ
確かに、Githubのコメントで追記しているのでコード上でのコメントでは不要だと納得できました！
こちらで修正しました！
[c1f8337](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/c1f8337d0738bb7c1862dfc7a98a8550ad9b7126)

2023-10-17 22:58 UTC, iseruuuuu commented on lib/data_source/weather_data_source.dart
> +    return jsonDecode(weather) as Map<String, dynamic>;
なるほど。勉強になります🤗
WeatherRequest や WeatherResultのテストコードを書いてみました。


[839d165](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/839d165be49f8afc81b6846bffd063c409cfac30)

2023-10-17 22:59 UTC, iseruuuuu commented on test/repository/weather_repository_test.dart
> +  });
Riverpodを使わずにテストを書いてみたところ期待通りに成功できたのでこちらで修正してみました！
[695ab7b](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/695ab7bb877966d28e26b0c1720373befc8812a7)

2023-10-17 23:00 UTC, iseruuuuu commented on test/repository/weather_repository_test.dart
> +    };
理解できました！こちらで修正しました！
[19eebc9](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/19eebc9afa7adae714e403704dbe7e192e67ec56)

2023-10-17 23:00 UTC, iseruuuuu commented on test/view_model/weather_view_model_test.dart
> +    );
こちらで削除してみました！
[384dbfe](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/384dbfe1fea72295c3ce7dca4e5ba5fe6fa07783)

2023-10-17 23:01 UTC, iseruuuuu commented on test/view_model/weather_view_model_test.dart
> +    container.dispose();
確かに、重複していましたね。。教えていただきありがとうございます！！
こちらで修正しました！
[d00ac32](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/d00ac32ad27d9a2960a7ce8b82b0ff6cf45cc879)

2023-10-17 23:02 UTC, iseruuuuu commented on test/view_model/weather_view_model_test.dart
> +    );
ほうほう。確かに教えていただいたコードの記載がいいと思えました。教えていただきありがとうございます！
こちらで修正しました！
[70c841c](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/70c841cc14dfda160805429ce13be21b0947c8a1)

2023-10-17 23:17 UTC, iseruuuuu commented on test/view_model/weather_view_model_test.dart
> +  });
reloadWeather() が失敗した場合のテストコードを
- 初期状態ー＞エラー
- データがある状態ー＞エラー

の2つのテストコードが必要そうであると判断し追記してみました！
[8ff4e94](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/8ff4e942f3c7ed45a204ff224cc79a2387ba87c6)

2023-10-18 00:54 UTC, blendthink commented on test/test_data/test_data.dart
> +  static const mockWeather = {
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
`weatherJson` と命名を合わせて `weatherMap` のほうがいいかもしれません。
```suggestion
  static const weatherMap = {
```

2023-10-18 00:54 UTC, blendthink commented on lib/data_source/weather_data_source.dart
> +    return jsonDecode(weather) as Map<String, dynamic>;
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg)
`encode()` と `decode()` のテストコードを削除することになったので、次のメソッド切り出しも不要になったと思いますので修正お願いします。

```dart
  @visibleForTesting
  String encode(WeatherRequest weatherRequest) {
    return jsonEncode(weatherRequest);
  }

  @visibleForTesting
  Map<String, dynamic> decode(String weather) {
    return jsonDecode(weather) as Map<String, dynamic>;
  }
```

2023-10-18 00:57 UTC, iseruuuuu commented on lib/data_source/weather_data_source.dart
> +    return jsonDecode(weather) as Map<String, dynamic>;
削除することを失念おりました。教えていただきありがとうございます🙇
こちらで修正できました！
[f554c14](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/f554c14434bbabc19c6a6d72106a218ed617833c)

2023-10-18 01:09 UTC, iseruuuuu commented on test/test_data/test_data.dart
> +  static const mockWeather = {
修正ほうがいいと納得できましたため、こちらで修正しました！
[17247b4](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/17247b43187c89e997fb227a9ac0c53b3ccd7bc6)

2023-10-18 06:58 UTC, blendthink reviewed
@iseruuuuu 
少し追加でコメントしましたので、ご確認お願いします 🙏

2023-10-18 06:58 UTC, blendthink commented on test/model/weather_request_test.dart
> +  test('success to do fromJson', () {
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
`WeatherRequest` がアプリ内でどのように使われているかというと、 `jsonEncode(weatherRequest)` で引数として渡されて、内部で `WeatherRequest` の `toJson()` が呼び出されているため、 `fromJson()` のテストではなく `toJson()` のテストを書いた方が適切です。

`toJson()` は外部の影響を受けない処理で内部でモックした方がいいものもないため、失敗時のテストは不要です。

2023-10-18 06:58 UTC, blendthink commented on test/model/weather_result_test.dart
> +  });
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
失敗にもさまざまなパターンがありますが、今回は設定ミスによって発生してしまうものをテストした方がメリットが大きくなりより適しています。
例えば、キーがスネークケースではなかったり、 `maxTemperature` の値の型が文字列だったり、もっと発展的なものだと、 `maxTemperature` より `minTemperature` の値が大きくなっていたりです。
今回のテストコードでは値も型も全然違うものになっていて、設定ミスによって発生しなさそうなものでそこまで大きなメリットはなさそうです。

このように、メリットがどのくらいあるかを考えてテストコードを書くようにすると、より効率よく安全に開発が進められるようになるためおすすめです。

2023-10-18 08:35 UTC, iseruuuuu commented on test/model/weather_request_test.dart
> +  test('success to do fromJson', () {
この辺りが理解していたつもりでしたが、わかっていなかったと自覚できました。教えていただきありがとうございました！（この辺りをアウトプットしたいので記事に書いて理解を深めたいです）

2023-10-18 08:36 UTC, iseruuuuu commented on test/model/weather_request_test.dart
> +  test('success to do fromJson', () {
こちらで修正しました！
[12b94c4](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/12b94c4547c9fa1d94bcfb47b696d9fc457a47cf)

2023-10-18 08:37 UTC, iseruuuuu commented on test/model/weather_request_test.dart
> +  test('success to do fromJson', () {
上のCommitで修正はしたものの、以下の記載について理解できませんでした。（明日もう一度読み直して理解したいと思っています🙇）
```
toJson() は外部の影響を受けない処理で内部でモックした方がいいものもないため、失敗時のテストは不要です
```

2023-10-18 09:44 UTC, blendthink commented on test/model/weather_request_test.dart
> +    ).toJson();
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
↓の部分がテストデータで、比較するときに使っている `weatherRequestData` はテストデータではなく期待値かなと思います、、！
```dart
const WeatherRequest(
 area: 'Kanagawa',
 date: '2023-10-12T12:00:00+09:00',
)
```

2023-10-18 22:55 UTC, iseruuuuu commented on test/model/weather_request_test.dart
> +    ).toJson();
教えていただきありがとうございます🙇
自分でも理解できるように、わかりやすく修正してみました！認識が間違っていましたら教えていただけると幸いです！
[f0dde32](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/f0dde321753234601787f9397e7546dbb5c4133d)

2023-10-19 01:12 UTC, iseruuuuu commented on test/model/weather_result_test.dart
> +  });
ご指摘いただきありがとうございます。`メリットがどのくらいあるかを考えてテストコードを書く`考え方がなかなか明確にならずに修正に時間がかかってしまいました。。

今回、自分なりに大きなメリットがあるテストを考えて、記載してみました。
お手隙の際にご確認お願いします🙇
[f213d18](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/f213d182dc33275d069e23b8396ff4828345b87c)

2023-10-19 02:52 UTC, iseruuuuu commented on test/model/weather_request_test.dart
> +  test('success to do fromJson', () {
改めて見返してみたところ、理解することが納得して理解することができました！教えていただ気ありがとうございます！！！

2023-10-19 06:58 UTC, iseruuuuu commented on test/model/weather_result_test.dart
> +  });
こちらの記載ですが、Json型のデータに不足しているパターンはいくつかありますが、ひとまず、一つのテストケースを書いてみました。
もし、他のテストケースも記載した方がよければ教えていただけると幸いです🙇

2023-10-19 06:58 UTC, iseruuuuu commented on test/model/weather_result_test.dart
> +    };
このようなデータは`test_data.dart`に記載した方がいいと考えていましたが、ミスが多く発覚したため、別のファイルで記載ではなくこちらのファイルで記載することにしました。
（他の同様なので他は割愛させていただきます🙇）

2023-10-19 06:58 UTC, iseruuuuu commented on test/model/weather_result_test.dart
> +  });
こちらのテストでは、３つのkeyがlowerCamelになっている場合のテストを書きましたが、別のテストケースも網羅できていると考えたため、一つの記載をしました。

2023-10-19 07:06 UTC, iseruuuuu commented
@blendthink 
先ほどはペアプロいただきありがとうございます！！
教えていただいたことを参考にし、記載をしてみました。お手隙の際にご確認お願い致します🙇

2023-10-19 07:06 UTC, iseruuuuu commented
@blendthink
先ほどはペアプロいただきありがとうございます！！
教えていただいたことを参考にし、記載をしてみました。お手隙の際にご確認お願い致します🙇

2023-10-20 08:11 UTC, blendthink commented on test/model/weather_request_test.dart
> +    expect(result, matcherWeatherRequest);
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
`expectedWeatherRequest` はあくまでもテスト用のデータかなと思うので、期待される WeatherRequest という命名は違和感があります。どちらかといえば `matcherWeatherRequest` が `expectedWeatherRequest` という命名のほうがしっくりきます。

どういう WeatherRequest なのかを表せるような命名にするか、単なるテストデータなので、他のテストと同様にローカル変数として `weatherResultData` というように定義してしまったほうがより分かりやすくなって良さそうです！

2023-10-20 08:12 UTC, blendthink commented on test/model/weather_result_test.dart
> +  });
そこまで発生する可能性は高くないかなと思いますので、いったんこのケースだけでいいと思います！

2023-10-20 08:18 UTC, iseruuuuu commented on test/model/weather_request_test.dart
> +    expect(result, matcherWeatherRequest);
修正をするのを忘れていました🙇
また、より詳しい説明のおかげで理解できた上で修正することができました！ありがとうございます！！
こちらで修正しました！
[e2a5349](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/e2a5349298bd4b996e00ea2a6b67845860b2aa37)

2023-10-20 08:28 UTC, blendthink reviewed
@iseruuuuu 
いくつかコメントしましたのでご確認お願いします 🙏

2023-10-20 08:28 UTC, blendthink commented on test/model/weather_result_test.dart
> +  test('valueの型や値が間違っており、fromJsonができない', () {
![good-badge](https://img.shields.io/badge/review-good-blightgreen.svg)
このように記載しているとどのようなテストを行っているか分かりやすくなっていいですね✨

2023-10-20 08:28 UTC, blendthink commented on test/view_model/weather_view_model_test.dart
> +  });
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg)
ここも `create()` を利用できそうです。
また、直接 `build()` メソッドを呼んでしまうと通常の状態の確認方法ではなく、単なる `build()` メソッドのテストになってしまうため注意が必要です。

```dart
  test('Check initial status', () {
    final viewModel = create();
    expect(
      viewModel.state,
      const WeatherScreenState.initial(),
    );
  });
```

2023-10-20 08:28 UTC, blendthink commented on test/view_model/weather_view_model_test.dart
> +      state,
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
このように書くとすっきりしそうです。
```suggestion
    final viewModel = create()..reloadWeather();
    expect(
      viewModel.state,
```

2023-10-20 08:28 UTC, blendthink commented on test/view_model/weather_view_model_test.dart
> +      state,
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
このように書くとすっきりしそうです。
```suggestion
    final viewModel = create()..reloadWeather();
    expect(
      viewModel.state,
```

2023-10-20 08:28 UTC, blendthink commented on test/view_model/weather_view_model_test.dart
> +    );
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg) 
このように書くとすっきりしそうです。
```suggestion
    final viewModel = create()..reloadWeather();
    final beforeState = viewModel.state;

    when(mockWeatherRepository.getWeather(any)).thenReturn(
      const Result.failure('error'),
    );
    viewModel.reloadWeather();
    final currentState = viewModel.state;
    expect(
      currentState,
      beforeState,
    );
```

2023-10-23 00:30 UTC, iseruuuuu commented on test/view_model/weather_view_model_test.dart
> +  });
ご指摘いただきありがとうございます🙇`build()`メソッドを意図せずに使用していました。
ここでのテストでは、`build()`ではなく`viewModel.state`の方が初期の状態を確認するテストとしては適切であると納得することができました。
こちらで修正しました！
[f3cd328](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/f3cd328474f5c0e2d22c3d4e2ac4ba669d5f581e)

2023-10-23 00:30 UTC, iseruuuuu commented on test/view_model/weather_view_model_test.dart
> +      state,
教えていただきありがとうございます！
カスケード演算子が同じオブジェクトに対するメソッドの実行の省略できることは知っていましたが、`create().reloadWeather();`と`create()..reloadWeather()`だと型が変わることは認知していませんでした。とても勉強になりました！
こちらで修正しました！
[baf6579](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/baf6579477958985b298890be551e591c35ecc2d)

2023-10-23 00:30 UTC, iseruuuuu commented on test/view_model/weather_view_model_test.dart
> +      state,
こちらで修正できました！
[d8a09a1](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/d8a09a1428c4397badf6e840c924003b273bc93e)

2023-10-23 00:30 UTC, iseruuuuu commented on test/view_model/weather_view_model_test.dart
> +    );
教えていただいたコードの方が可読性がとても高いと強く感じることができました🙇ありがとうございます！
こちらで修正してみました！
[3d9830c](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/3d9830c5145075c193116510c86a47dadaae813f)

2023-10-23 02:27 UTC, blendthink approved these changes
１点だけコメントしていますが、概ね問題ないと思いましたので Approve させていただきます！
ご対応ありがとうございました！

2023-10-23 02:27 UTC, blendthink commented on test/test_data/test_data.dart
> +  static const invalidWeatherRequestData = {
![nits-badge](https://img.shields.io/badge/review-nits-orange.svg)
使用していなさそうなので、削除お願いします 🙏

2023-10-23 03:13 UTC, iseruuuuu commented on test/test_data/test_data.dart
> +  static const invalidWeatherRequestData = {
教えていただいた修正に集中しすぎてしまい、見逃していました。。教えていただきありがとうございます！！！
以前、ペアプロで教えていただいた、「`test_data.dart`に値を何ふり構わず追加するのはあまり良くない」という話を思い出して、追加しすぎて使わないものを見逃しまうデメリットもあるなとこのコメントから学ぶことができました！！
こちらのCommitで修正できました！！

[7ea4299](https://github.com/iseruuuuu/flutter_yumemi_training_app/pull/27/commits/7ea429913c9e6346a1d40aadd8b51ae54100e8e4)

2023-10-23 06:41 UTC, iseruuuuu commented
Approvalいただきありがとうございます！！
マージさせていただきます！！

2023-10-23 06:44 UTC, merged